#!/usr/bin/awk -f

# take a twitter thread and make it flat text

# initial spaces only in interesting parts
# except for first and last:

# Foo Bar baz @foo_bar ...
# ...
#  line0
# ...
#  Foo Bar baz @foo_bar ...
# ...
#  line1
# ...
# lineN

NR == 1 { 
        split($0, a, "@")
        s = a[1]
        split("", a)
        n = length(s)
        next
}

/^ / {
        b = substr($0, 2, n)
        if (b == s) next

        print
}
